# ./docker-compose.yml

version: '3'

services:
  graphql:
    image: surfingdirt/graphql:22
    container_name: graphql
    volumes:
      - /home/mikael/www/beta/graphql/:/var/www/html/
    ports:
      - "8004:4000"
    stdin_open: true
    tty: true