# ./docker-compose.beta.yml

version: '3'

services:
  graphql_beta:
    environment:
            - GOOGLE_APPLICATION_CREDENTIALS
            - NODE_ENV=beta
    image: surfingdirt/graphql:40
    container_name: graphql_beta
    volumes:
      - /home/mikael/www/beta/graphql/:/var/www/html/
    ports:
      - "8004:4000"
    stdin_open: true
    tty: true