# ./docker-compose.production.yml

version: '3'

services:
  graphql_production:
    environment:
            - GOOGLE_APPLICATION_CREDENTIALS
            - NODE_ENV=production
    image: surfingdirt/graphql:40
    container_name: graphql_production
    volumes:
      - /home/mikael/www/production/graphql/:/var/www/html/
    ports:
      - "8003:4000"
    stdin_open: true
    tty: true